services:
  - type: web
    name: skillproof-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
      - key: MONGO_URI
        sync: false

  - type: web
    name: skillproof-frontend
    env: static
    rootDir: frontend
    buildCommand: npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: skillproof-backend
          property: url
